import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/navbar";

const inter = Inter({ subsets: ["latin"] });

interface Metadata {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html>
      <body>
    <Navbar />
    <div className="flex justify-center items-center min-h-screen bg-black">
      <div className="w-4/5">
        {children}
      </div>
    </div>
  </body>
  </html>
  );
}

export default Layout